title: Tommaso Montedoro
email: tommaso.montedoro@gmail.com
logo: /assets_img/IMGP7232.JPG
# description: text below image
# show_downloads: true
theme: jekyll-theme-minimal
# remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
sass:
  load_paths:
    - _sass
  style: compressed
includes:
  - style.css
